[package]
name = "tari_template_abi"
version = "0.35.1"
edition = "2021"

[dependencies]
tari_bor = { path = "../tari_bor", default-features = false }

[features]
default = ["std"]
std = ["tari_bor/std"]
